In [ ]:
!pip show numpy

In [ ]:
import numpy as np

###creating arrays using numpy
# l###

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

In [ ]:
import numpy as np
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

In [ ]:
# np.arange(0,10,2).reshape(5,1)
# np.ones((3,4))
np.eye(3)

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("addition",arr1+arr2)
print("substraction",arr1-arr2)
print("multiplication",arr1*arr2)
print("division",arr1/arr2)

In [ ]:
# arr=np.array([2,3,4,5,6])
# print(np.sqrt(arr))
# print(np.exp(arr))
# print(np.sin(arr))
# print(np.log(arr))

#Slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n", arr)

In [ ]:
# # arr[0]
# arr[1:,2:]
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:3])

In [ ]:
arr[0,0]=100
print(arr)
arr[1:]=20
print(arr)

In [ ]:
#Normalization
#To have a mean 0 and standard devaition 1

data=np.array([1,2,3,4,5])

#Mean and Standard deviation
mean=np.mean(data)
standard_devn=np.std(data)


#Normalize the data
normalized_data=(data-mean)/standard_devn

print("Normalized data :", normalized_data)

var=np.var(data)
print(var)

In [ ]:
#Logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=9)]
# print(rest)

In [ ]:
import pandas as pd

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

In [ ]:
# data={'a':1,'b':2,'c':3}
# sr=pd.Series(data)
# print(sr)

data=[10,20,30]
index=['a','b','c']
pd.Series(data,index)

In [ ]:
#DataFrame

#Create a dataframe from a dictionary of list

# data={
#     'Name':['Sidd','Vini','CR7','Messi'],
#     'Age':[25,40,30,12],
#     'City':['Banglore','LA','New York','Pensilvenuia']
# }

df=pd.DataFrame(data)
print(df)
print(type(df))

In [ ]:
# import numpy as np
# dff=np.array(df)
# print(dff)

data=[
    {'Name':'Siddy','Age':122,'City':'Delhi'},
    {'Name':'cr7','Age':23,'City':'madrid'},
    {'Name':'neymar','Age':34,'City':'santos'},
    {'Name':'messi','Age':56,'City':'bruenoares'},
]

dfff=pd.DataFrame(data)
print(dfff)
print(type(dfff))

In [ ]:
dd=pd.read_csv('data.csv')
dd.head(5)
dd.tail(3)

In [ ]:
#Accessing data from dataframe
data
# df['Name']
df.iloc[0][2]

In [ ]:
#Accessing a specified element

# df.at[1,'Age']
# df.at[2,'Name']

df.iat[2,2]

In [ ]:
df['Salary']=[1000,2000,3000,334234]
df

In [ ]:
# df.drop('Salary',axis=1,inplace=True)
#Add salary again
df['Age']=df['Age']+1

In [ ]:
dd.describe()

In [ ]:
import pandas as pd

de=pd.read_csv('data.csv')
de.head(5)
de.tail(5)
de.describe()
de.dtypes

In [ ]:
#Handling missing values
# de[de.isnull()]
# de.isnull().any()
de.isnull().sum()

In [ ]:
de.fillna(2)

In [ ]:
de['Duration_fillNA']=de['Duration'].fillna(de['Duration'].mean())
de

In [ ]:
# de.dtypes
#Renaming columns

de=de.rename(columns={'Date':'Diet Date'})
de.head(5)

#Changing Datatype
de['Pulse_new']=de['Pulse'].astype(float)
de['calories_new']=de['Calories'].fillna(de['Calories'].mean()).astype(int)
de.head(5)

In [ ]:
# de['New Pulse']=de['Pulse'].apply(lambda x:x**2)
# de

#Data aggregating and grouping

# grp_mean=de.groupby('Calories')['Pulse'].mean()
# print(grp_mean)

grp_sum=de.groupby(['Duration'],['maxpulse'])['Pulse'].sum()
property(grp_sum)

In [ ]:
grp_agg=de.groupby('Pulse')['Maxpulse'].agg(['mean','sum','count'])
grp_agg

In [ ]:
#MErging and Joining
df1=pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2=pd.DataFrame({'Key':['A','B','D'],'Value1':[4,5,6]})

pd.merge(df1,df2,on="Key",how='outer')

In [ ]:
import pandas as pd
from io import StringIO

Data = '[{"name": "Siddhant", "age": 21, "is_student": true, "skills": ["Python", "Django", "SQL"]}]'

df = pd.read_json(StringIO(Data))
print(df)

In [ ]:
df.to_json(orient='index')

In [ ]:
url="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)
df

In [ ]:
url="https://fbref.com/en/players/dea698d9/Cristiano-Ronaldo"
pd.read_html(url,match="Country",header=0)[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Playing Time,Playing Time.1,Playing Time.2,...,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4,Per 90 Minutes.5,Per 90 Minutes.6,Per 90 Minutes.7,Per 90 Minutes.8,Per 90 Minutes.9,Unnamed: 35
0,Season,Age,Squad,Country,Comp,LgRank,MP,Starts,Min,90s,...,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches
1,2002-2003,17,Sporting CP,pt POR,1. Primeira Liga,3rd,25,11,1080,12.0,...,0.25,0.50,0.25,0.50,NaN,NaN,NaN,NaN,NaN,Matches
2,2003-2004,18,Manchester Utd,eng ENG,1. Premier League,3rd,29,15,1555,17.3,...,0.23,0.46,0.23,0.46,NaN,NaN,NaN,NaN,NaN,Matches
3,2004-2005,19,Manchester Utd,eng ENG,1. Premier League,3rd,33,25,2423,26.9,...,0.15,0.33,0.19,0.33,NaN,NaN,NaN,NaN,NaN,Matches
4,2005-2006,20,Manchester Utd,eng ENG,1. Premier League,2nd,33,24,2286,25.4,...,0.24,0.59,0.35,0.59,NaN,NaN,NaN,NaN,NaN,Matches
5,2006-2007,21,Manchester Utd,eng ENG,1. Premier League,1st,34,31,2781,30.9,...,0.26,0.81,0.45,0.71,NaN,NaN,NaN,NaN,NaN,Matches
6,2007-2008,22,Manchester Utd,eng ENG,1. Premier League,1st,34,31,2747,30.5,...,0.20,1.21,0.88,1.08,NaN,NaN,NaN,NaN,NaN,Matches
7,2008-2009,23,Manchester Utd,eng ENG,1. Premier League,1st,33,31,2742,30.5,...,0.20,0.79,0.46,0.66,NaN,NaN,NaN,NaN,NaN,Matches
8,2009-2010,24,Real Madrid,es ESP,1. La Liga,2nd,29,28,2461,27.3,...,0.26,1.21,0.80,1.06,NaN,NaN,NaN,NaN,NaN,Matches
9,2010-2011,25,Real Madrid,es ESP,1. La Liga,2nd,34,32,2914,32.4,...,0.28,1.51,0.99,1.27,NaN,NaN,NaN,NaN,NaN,Matches
10,2011-2012,26,Real Madrid,es ESP,1. La Liga,1st,38,37,3350,37.2,...,0.32,1.56,0.91,1.24,NaN,NaN,NaN,NaN,NaN,Matches
11,2012-2013,27,Real Madrid,es ESP,1. La Liga,2nd,34,30,2716,30.2,...,0.33,1.46,0.93,1.26,NaN,NaN,NaN,NaN,NaN,Matches
12,2013-2014,28,Real Madrid,es ESP,1. La Liga,3rd,30,30,2534,28.2,...,0.32,1.42,0.89,1.21,NaN,NaN,NaN,NaN,NaN,Matches
13,2014-2015,29,Real Madrid,es ESP,1. La Liga,2nd,35,35,3100,34.4,...,0.46,1.86,1.10,1.57,NaN,NaN,NaN,NaN,NaN,Matches
14,2015-2016,30,Real Madrid,es ESP,1. La Liga,2nd,36,36,3183,35.4,...,0.25,1.24,0.82,1.07,NaN,NaN,NaN,NaN,NaN,Matches
15,2016-2017,31,Real Madrid,es ESP,1. La Liga,1st,29,29,2539,28.2,...,0.21,1.10,0.67,0.89,NaN,NaN,NaN,NaN,NaN,Matches
16,2017-2018,32,Real Madrid,es ESP,1. La Liga,3rd,27,27,2285,25.4,...,0.20,1.22,0.91,1.10,0.99,0.20,1.19,0.86,1.06,Matches
17,2018-2019,33,Juventus,it ITA,1. Serie A,1st,31,30,2688,29.9,...,0.27,0.97,0.54,0.80,0.74,0.15,0.90,0.58,0.74,Matches
18,2019-2020,34,Juventus,it ITA,1. Serie A,1st,33,33,2917,32.4,...,0.15,1.11,0.59,0.74,0.88,0.20,1.08,0.57,0.76,Matches
19,2020-2021,35,Juventus,it ITA,1. Serie A,4th,33,31,2802,31.1,...,0.06,1.00,0.74,0.80,0.89,0.12,1.01,0.69,0.81,Matches
20,2021-2022,36,Juventus,it ITA,1. Serie A,4th,1,0,31,0.3,...,0.00,0.00,0.00,0.00,0.44,0.17,0.61,0.44,0.61,Matches
21,2021-2022,36,Manchester Utd,eng ENG,1. Premier League,6th,30,27,2456,27.3,...,0.11,0.77,0.55,0.66,0.65,0.11,0.75,0.56,0.67,Matches
22,2022-2023,37,Manchester Utd,eng ENG,1. Premier League,3rd,10,4,525,5.8,...,0.00,0.17,0.17,0.17,0.32,0.07,0.40,0.32,0.40,Matches
23,2022-2023,37,Al-Nassr,sa KSA,1. Pro League,2nd,16,16,1433,15.9,...,0.13,1.00,0.57,0.69,NaN,NaN,NaN,NaN,NaN,Matches
24,2023-2024,38,Al-Nassr,sa KSA,1. Pro League,2nd,31,30,2645,29.4,...,0.37,1.57,0.92,1.29,NaN,NaN,NaN,NaN,NaN,Matches
25,2024-2025,39,Al-Nassr,sa KSA,1. Saudi Professional League,3rd,30,30,2620,29.1,...,0.10,0.96,0.58,0.69,NaN,NaN,NaN,NaN,NaN,Matches
26,23 Seasons,23 Seasons,5 Clubs,NaN,5 Leagues,NaN,728,653,58813,653.5,...,0.24,1.11,0.69,0.93,0.81,0.15,0.96,0.63,0.79,NaN
27,NaN,NaN,NaN,Country,Comp,LgRank,MP,Starts,Min,90s,...,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches
28,Real Madrid (9 Seasons),Real Madrid (9 Seasons),Real Madrid (9 Seasons),NaN,1 League,NaN,292,284,25082,278.7,...,0.30,1.41,0.90,1.19,0.99,0.20,1.19,0.86,1.06,NaN
29,Manchester Utd (8 Seasons),Manchester Utd (8 Seasons),Manchester Utd (8 Seasons),NaN,1 League,NaN,236,188,17515,194.6,...,0.19,0.72,0.46,0.65,0.59,0.10,0.69,0.52,0.62,NaN
30,Juventus (4 Seasons),Juventus (4 Seasons),Juventus (4 Seasons),NaN,1 League,NaN,98,94,8438,93.8,...,0.16,1.02,0.62,0.78,0.84,0.16,1.00,0.61,0.77,NaN
31,Al-Nassr (3 Seasons),Al-Nassr (3 Seasons),Al-Nassr (3 Seasons),NaN,1 League,NaN,77,76,6698,74.4,...,0.21,1.21,0.71,0.93,NaN,NaN,NaN,NaN,NaN,NaN
32,Sporting CP (1 Season),Sporting CP (1 Season),Sporting CP (1 Season),NaN,1 League,NaN,25,11,1080,12.0,...,0.25,0.50,0.25,0.50,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,La Liga (9 Seasons),La Liga (9 Seasons),La Liga (9 Seasons),NaN,NaN,NaN,292,284,25082,278.7,...,0.30,1.41,0.90,1.19,0.99,0.20,1.19,0.86,1.06,NaN
35,Premier League (8 Seasons),Premier League (8 Seasons),Premier League (8 Seasons),NaN,NaN,NaN,236,188,17515,194.6,...,0.19,0.72,0.46,0.65,0.59,0.10,0.69,0.52,0.62,NaN
36,Serie A (4 Seasons),Serie A (4 Seasons),Serie A (4 Seasons),NaN,NaN,NaN,98,94,8438,93.8,...,0.16,1.02,0.62,0.78,0.84,0.16,1.00,0.61,0.77,NaN
37,Saudi Professional League (3 Seasons),Saudi Professional League (3 Seasons),Saudi Professional League (3 Seasons),NaN,NaN,NaN,77,76,6698,74.4,...,0.21,1.21,0.71,0.93,NaN,NaN,NaN,NaN,NaN,NaN
38,Primeira Liga (1 Season),Primeira Liga (1 Season),Primeira Liga (1 Season),NaN,NaN,NaN,25,11,1080,12.0,...,0.25,0.50,0.25,0.50,NaN,NaN,NaN,NaN,NaN,NaN